- name: link_neovim
  command:
    cmd: "ln -s /opt/nvim-linux-x86_64/bin/nvim /usr/bin/nvim"

- name: create_docker_directory
  tags: docker
  command:
    cmd: "mkdir /home/spektre/docker"

- name: run_komodo
  tags: komodo
  command:
    chdir: /home/spektre/docker/komodo
    cmd: "docker compose up -d"
